name: open_weather_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  dio: ^5.3.2
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_ui_auth: ^1.6.2
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  geolocator: 9.0.2
  geolocator_android: 4.2.2
  intl: ^0.18.0
  permission_handler: ^10.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Medium.ttf
