// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkFBmk8a7QNhY6DipJ8F0LvEmoFiSbyXM',
    appId: '1:523216109503:web:65955ce0bd137d94d7ab0a',
    messagingSenderId: '523216109503',
    projectId: 'weather-app-6ccce',
    authDomain: 'weather-app-6ccce.firebaseapp.com',
    storageBucket: 'weather-app-6ccce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5AZ0sjqa7Ogb7LkLs_ibJnbYrjmXURSg',
    appId: '1:523216109503:android:2b65be70739ae098d7ab0a',
    messagingSenderId: '523216109503',
    projectId: 'weather-app-6ccce',
    storageBucket: 'weather-app-6ccce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC-edK0dqhsv5pfSFzc1q4xAr9hN1846I',
    appId: '1:523216109503:ios:5535a2f259734ff7d7ab0a',
    messagingSenderId: '523216109503',
    projectId: 'weather-app-6ccce',
    storageBucket: 'weather-app-6ccce.appspot.com',
    iosClientId: '523216109503-fm0vs33p6eg24q1rm57lfrvgrqe2rkkp.apps.googleusercontent.com',
    iosBundleId: 'com.example.openWeatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC-edK0dqhsv5pfSFzc1q4xAr9hN1846I',
    appId: '1:523216109503:ios:0242ad2af099b9f9d7ab0a',
    messagingSenderId: '523216109503',
    projectId: 'weather-app-6ccce',
    storageBucket: 'weather-app-6ccce.appspot.com',
    iosClientId: '523216109503-a94pdrs4krfnu7n2jqh6fj1mo7qruvbs.apps.googleusercontent.com',
    iosBundleId: 'com.example.openWeatherApp.RunnerTests',
  );
}
